### ISSUE TITLE
`bool` fields sometimes true when the corresponding flag is not given

### ISSUE THREAD

**Issue by AuroransSolis** [TeXitoi/structopt#410] opened 2020-07-23 02:38 UTC
Hello, I've been making liberal use of `structopt` in [a project of mine](https://github.com/AuroransSolis/osu-db-manager), but I'm running into an issue where some flags end up as `true` when they're not passed in as arguments. Using my project as an example, if I use the arguments `search osu-search --show-number-of-beatmaps`, some other flags end up as `true` (specifically the `difficulty` and `unplayed` fields on the `BeatmapMask` struct in `src/masks/osu_mask.rs`) despite the fact that their flags are missing:
```
number of beatmaps: 89929
    difficulty: Hard
    unplayed: true
    difficulty: Normal
    unplayed: true
    difficulty: Gen's Futsuu
    unplayed: true
    difficulty: Gen's Muzukashii
    unplayed: true
    difficulty: Inner Oni
```
From this output, I can see that it's acting as though I'd used `search osu-search --show-number-of-beatmaps --show-difficulty --show-unplayed` as the arguments. I've also gone and printed out the value of those two fields from the struct immediately after the command line arguments are parsed, and they're always `true` regardless of the provided arguments. [Here's a link to the struct in question](https://github.com/AuroransSolis/osu-db-manager/blob/master/src/masks/osu_mask.rs#L3-L125), and [here's a link to a Pastebin dump](https://pastebin.com/sK6KUNMU) of a diagram I've used to check how I set things up in case it helps.

I know this is the point where I'm supposed to post a link to a smaller example that produces the same issue, but I've honestly struggled to create one so far. I'll keep going and update this if I end up coming up with something.

**Comment by CreepySkeleton** [comment] 2020-07-23 05:18
I couldn't reproduce this:
```rust
use structopt::StructOpt;

#[derive(Copy, Clone, Debug, StructOpt)]
pub struct BeatmapMask {
    #[structopt(long = "show-entry-size")]
    pub entry_size: bool,
    #[structopt(long = "show-artist-name")]
    pub artist_name: bool,
    #[structopt(long = "show-artist-name-unicode")]
    pub artist_name_unicode: bool,
    #[structopt(long = "show-song-title")]
    pub song_title: bool,
    #[structopt(long = "show-song_title-unicode")]
    pub song_title_unicode: bool,
    #[structopt(long = "show-creator-name")]
    pub creator_name: bool,
    #[structopt(long = "show-difficulty")]
    pub difficulty: bool,
    #[structopt(long = "show-audio-file-name")]
    pub audio_file_name: bool,
    #[structopt(long = "show-md5-beatmap-hash")]
    pub md5_beatmap_hash: bool,
    #[structopt(long = "show-dotosu-file-name")]
    pub dotosu_file_name: bool,
    #[structopt(long = "show-ranked-status")]
    pub ranked_status: bool,
    #[structopt(long = "show-number-of-hitcircles")]
    pub number_of_hitcircles: bool,
    #[structopt(long = "show-number-of-sliders")]
    pub number_of_sliders: bool,
    #[structopt(long = "show-number-of-spinners")]
    pub number_of_spinners: bool,
    #[structopt(long = "show-last_modification-time")]
    pub last_modification_time: bool,
    #[structopt(long = "show-approach-rate")]
    pub approach_rate: bool,
    #[structopt(long = "show-circle-size")]
    pub circle_size: bool,
    #[structopt(long = "show-hp-drain")]
    pub hp_drain: bool,
    #[structopt(long = "show-overall-difficulty")]
    pub overall_difficulty: bool,
    #[structopt(long = "show-slider-velocity")]
    pub slider_velocity: bool,
    #[structopt(long = "show-num-mod-combo-star-ratings-standard")]
    pub num_mod_combo_star_ratings_standard: bool,
    #[structopt(long = "show-mod-combo-star-ratings-standard")]
    pub mod_combo_star_ratings_standard: bool,
    #[structopt(long = "show-num-mod-combo-star-ratings-taiko")]
    pub num_mod_combo_star_ratings_taiko: bool,
    #[structopt(long = "show-mod-combo-star-ratings-taiko")]
    pub mod_combo_star_ratings_taiko: bool,
    #[structopt(long = "show-num-mod-combo-star-ratings-ctb")]
    pub num_mod_combo_star_ratings_ctb: bool,
    #[structopt(long = "show-mod-combo-star-ratings-ctb")]
    pub mod_combo_star_ratings_ctb: bool,
    #[structopt(long = "show-num-mod-combo-star-ratings-mania")]
    pub num_mod_combo_star_ratings_mania: bool,
    #[structopt(long = "show-mod-combo-star-ratings-mania")]
    pub mod_combo_star_ratings_mania: bool,
    #[structopt(long = "show-drain-time")]
    pub drain_time: bool,
    #[structopt(long = "show-total-time")]
    pub total_time: bool,
    #[structopt(long = "show-preview-offset-from-start-ms")]
    pub preview_offset_from_start_ms: bool,
    #[structopt(long = "show-num-timing-points")]
    pub num_timing_points: bool,
    #[structopt(long = "show-timing-points")]
    pub timing_points: bool,
    #[structopt(long = "show-beatmap-id")]
    pub beatmap_id: bool,
    #[structopt(long = "show-beatmap-set-id")]
    pub beatmap_set_id: bool,
    #[structopt(long = "show-thread-id")]
    pub thread_id: bool,
    #[structopt(long = "show-standard-grade")]
    pub standard_grade: bool,
    #[structopt(long = "show-taiko-grade")]
    pub taiko_grade: bool,
    #[structopt(long = "show-ctb-grade")]
    pub ctb_grade: bool,
    #[structopt(long = "show-mania-grade")]
    pub mania_grade: bool,
    #[structopt(long = "show-local-offset")]
    pub local_offset: bool,
    #[structopt(long = "show-stack-leniency")]
    pub stack_leniency: bool,
    #[structopt(long = "show-gameplay-mode")]
    pub gameplay_mode: bool,
    #[structopt(long = "show-song-source")]
    pub song_source: bool,
    #[structopt(long = "show-song-tags")]
    pub song_tags: bool,
    #[structopt(long = "show-online-offset")]
    pub online_offset: bool,
    #[structopt(long = "show-font-used-for-song-title")]
    pub font_used_for_song_title: bool,
    #[structopt(long = "show-unplayed")]
    pub unplayed: bool,
    #[structopt(long = "show-last-played")]
    pub last_played: bool,
    #[structopt(long = "show-is-osz2")]
    pub is_osz2: bool,
    #[structopt(long = "show-beatmap-folder-name")]
    pub beatmap_folder_name: bool,
    #[structopt(long = "show-last-checked-against-repo")]
    pub last_checked_against_repo: bool,
    #[structopt(long = "show-ignore-beatmap-sound")]
    pub ignore_beatmap_sound: bool,
    #[structopt(long = "show-ignore-beatmap-skin")]
    pub ignore_beatmap_skin: bool,
    #[structopt(long = "show-disable-storyboard")]
    pub disable_storyboard: bool,
    #[structopt(long = "show-disable-video")]
    pub disable_video: bool,
    #[structopt(long = "show-visual-override")]
    pub visual_override: bool,
    #[structopt(long = "show-unknown-short")]
    pub unknown_short: bool,
    #[structopt(long = "show-offset-from-song-start-in-editor-ms")]
    pub offset_from_song_start_in_editor_ms: bool,
    #[structopt(long = "show-mania-scroll-speed")]
    pub mania_scroll_speed: bool,
}

fn main() {
    // no args passed 
    println!("{:#?}", BeatmapMask::from_iter_safe(&["test"]));
}
```

```
Ok(
    BeatmapMask {
        entry_size: false,
        artist_name: false,
        artist_name_unicode: false,
        song_title: false,
        song_title_unicode: false,
        creator_name: false,
        difficulty: false,
        audio_file_name: false,
        md5_beatmap_hash: false,
        dotosu_file_name: false,
        ranked_status: false,
        number_of_hitcircles: false,
        number_of_sliders: false,
        number_of_spinners: false,
        last_modification_time: false,
        approach_rate: false,
        circle_size: false,
        hp_drain: false,
        overall_difficulty: false,
        slider_velocity: false,
        num_mod_combo_star_ratings_standard: false,
        mod_combo_star_ratings_standard: false,
        num_mod_combo_star_ratings_taiko: false,
        mod_combo_star_ratings_taiko: false,
        num_mod_combo_star_ratings_ctb: false,
        mod_combo_star_ratings_ctb: false,
        num_mod_combo_star_ratings_mania: false,
        mod_combo_star_ratings_mania: false,
        drain_time: false,
        total_time: false,
        preview_offset_from_start_ms: false,
        num_timing_points: false,
        timing_points: false,
        beatmap_id: false,
        beatmap_set_id: false,
        thread_id: false,
        standard_grade: false,
        taiko_grade: false,
        ctb_grade: false,
        mania_grade: false,
        local_offset: false,
        stack_leniency: false,
        gameplay_mode: false,
        song_source: false,
        song_tags: false,
        online_offset: false,
        font_used_for_song_title: false,
        unplayed: false,
        last_played: false,
        is_osz2: false,
        beatmap_folder_name: false,
        last_checked_against_repo: false,
        ignore_beatmap_sound: false,
        ignore_beatmap_skin: false,
        disable_storyboard: false,
        disable_video: false,
        visual_override: false,
        unknown_short: false,
        offset_from_song_start_in_editor_ms: false,
        mania_scroll_speed: false,
    },
)
```

I have three ideas:
1. An error somewhere in your code. This would be my bet.
2. Some miscompiled artifact interferes with incremental compilation. Run` cargo clean` and try again.
3. Divine intervention. Do you believe in God?

And I would _really_ love some minimized example here. By minimized I mean "the least possible amount of code unrelated to structopt itself".

**Comment by AuroransSolis** [comment] 2020-07-23 06:31
Unfortunately, a `cargo clean` and rebuild hasn't solved the issue. I'll go through my code again and try to make a minimal example elsewhere.

**Comment by CreepySkeleton** [comment] 2020-07-27 05:51
Any luck yet? I must admit I'm skeptical about the bug report because flags' handling is core functionality and used by almost everybody. If there's a bug in there, it must be something that's triggered only in very rare and special circumstances, or somebody would have reported it already. 

I tried to blindly run my would-be reproducer with a several permutations of the flags, and everything worked correctly. I'm strongly suspecting it's an error in your code at this point.

**Comment by AuroransSolis** [comment] 2020-07-28 03:35
Ah, sorry, I've been a bit busy lately, but after the end of this month I should be able to sit down for a bit and start trying to figure out what went wrong. Thanks for checking in, though!

**Comment by CreepySkeleton** [comment] 2020-08-09 17:23
So. 

Given the lack of reproducer and quite low probability of a bug like this staying unnoticed, I'm closing the issue as "an error in your code". If somebody could give me a clear reproducer that actually would give something to work with, feel free to open a new issue or reopen this one.

**Closed by CreepySkeleton** 2020-08-09 17:23 UTC

**Comment by AuroransSolis** [comment] 2020-08-16 09:26
Aha! I think figured it out! I believe it's because some fields shared names between the search/load setting structs. For instance, changing `#[structopt(long = "show-entry-size")]` to `#[structopt(name = "show-entry-size", long = "show-entry-size")]` in `src/mask/osu_mask.rs`. I did this for all flags across the various show structs, and that's seemed to have resolved the issue.

**Comment by TeXitoi** [comment] 2020-08-16 10:10
Do you use the name somewhere else, as in require_if, groups or things like that? Because in these call, the name must be used, not the option string. By default, the name is the raw field name. Maybe that's what cased you problems?

**Comment by AuroransSolis** [comment] 2020-08-16 10:14
Yeah, I'm pretty sure it's the reuse of raw field names that caused the issue.
