### ISSUE TITLE
Support structs as enum variants

### ISSUE THREAD

**Issue by gnzlbg** [TeXitoi/structopt#59] opened 2018-02-08 13:11 UTC
I have an application that started like this:

```rust
struct Options {
  field1: String, 
  ...
}
```

and then grew to support sub-commands, so I move it to:

```rust
enum Options {
    SubCommand0 { field1: String, ... }, 
    ...
}
```

This was very painful. Now matching on my `Options` looks like this:

```rust
match options { 
    subcommand0  { field1, ...} => {
        // I cannot reuse the API of my previous code here because
        // it expects a struct but I only have the fields
    }
    ...
}
```

[`gumdrop`](https://github.com/murarth/gumdrop) allows using structs as tuple struct enum fields this, for example, [see here](https://github.com/Arnavion/fac-rs/blob/gumdrop/src/main.rs#L83). This makes things much nicer because I just need to rename my old `Options` to `SubCommand0`, add it as a tuple struct field, and can reuse that in the rest of my code: 

```rust
struct SubCommand0 {
  field1: String, 
  ...
}

enum Options {
    SubCommand0(SubCommand0),
    ...
}

// logic:
match options { 
    SubCommand0(subcommand0_options) =>  {
        // No need to change the API of anything
    }
    ...
}
```

I think it would be huge if `structopt` could support this in 0.2. It would make using the `enums` for sub-commands infinitely nicer.

**Comment by TeXitoi** [comment] 2018-02-08 14:03
Duplicate of #38 that will be in v0.2

**Closed by TeXitoi** 2018-02-08 14:03 UTC

**Comment by gnzlbg** [comment] 2018-02-08 14:09
Ah didn't saw that one, thanks a lot for your work! `structopt` is really great!
