### ISSUE TITLE
Combining env and flag arguments doesn't work as expected

### ISSUE THREAD

**Issue by Kerollmops** [TeXitoi/structopt#305] opened 2019-12-10 14:35 UTC
When we add the `env` attribute on a `boolean` field, the command line argument, that must be considered as a flag, is considered as an attribute requiring a value.

```rust
#[derive(StructOpt)]
pub struct Opt {
    /// Do not send analytics.
    #[structopt(long, env = "NO_ANALYTICS")]
    pub no_analytics: bool,
}
```

Here is what StructOpt generate with the above configuration:

```
xxx-http 0.8.4

USAGE:
    xxx [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
        --no-analytics <no-analytics>    Do not send analytics. [env: NO_ANALYTICS=]
```

And here is what I expected:

```
xxx-http 0.8.4

USAGE:
    xxx [OPTIONS]

FLAGS:
    -h, --help             Prints help information
          --no-analytics   Do not send analytics. [env: NO_ANALYTICS]
    -V, --version          Prints version information
```

Is this behavior expected or is it not? Thank you for you help.

**Comment by CreepySkeleton** [comment] 2019-12-11 15:20
It isn't really clear what the expected behavior is from your comment. I'm going to assume it's all about 

* flags (long `bool` fields) do not take any value, the very fact `--no-analytics` is present raises the flag. **This is true in structopt**
* environment fallbacks for flags don't take any value. More specifically, the very fact the fallback env is defined (i.e you have `export NO_ANALYTICS=""` someplace above/before) raises the flag, it's assigned with.

Now, let's remember that `structopt` works on top of `clap`. If you use some feature with `structopt` - this feature must be available in `clap` in the first place. I believe what you're asking for is not possible with `clap`  because [`Arg::env` implies `Arg::takes_value(true)`](https://docs.rs/clap/2.32.0/clap/struct.Arg.html#method.env). Even if you reset `takes_value(false)` back it won't work, unfortunately. 

I'm closing this since it's entirely about `clap`, `structopt` has nothing to do with it.

Btw, there is [such a request in `clap` already](https://github.com/clap-rs/clap/issues/1476).

**Closed by CreepySkeleton** 2019-12-11 15:20 UTC

**Comment by Kerollmops** [comment] 2019-12-11 15:27
Ho! I already checked if it there was a related issue on Clap and didn't found anything.
I fallback on the issue page of StructOpt because I thought it was done by it, which is a dumb thought as this is clearly Calp which produce this help message.

I apology and subscribed to the clap issue at the same time :) Thank you!
