### ISSUE TITLE
Description of flattened struct overwrites app description

### ISSUE THREAD

**Issue by palant** [TeXitoi/structopt#539] opened 2024-05-08 09:11 UTC
Consider the following application:

```rust
use structopt::StructOpt;

/// Inner description
#[derive(Debug, StructOpt)]
struct OptInner {}

/// Outer description
#[derive(Debug, StructOpt)]
struct OptOuter {
    #[structopt(flatten)]
    inner: OptInner
}

fn main() {
    OptOuter::from_args();
}
```

Running `cargo run -- -h` produces the following help text:

```
test 0.1.0
Inner description

USAGE:
    test

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

Note that the application description belongs to `OptInner`, not `OptOuter` as expected. Running `cargo expand` shows the issue:

```rust
let app = app.about("Outer description");
let app = <OptInner as ::structopt::StructOptInternal>::augment_clap(app);
```

So this first applies the attributes of the outer structure and calls `augment_clap()` of the inner structure then which will overwrite them.

The equivalent clap code does that in reverse order, producing the correct result:

```rust
let __clap_app = <OptInner as clap::Args>::augment_args(__clap_app);
__clap_app.about("Outer description").long_about(None)
```

For reference: https://github.com/clap-rs/clap/issues/2527

**Comment by TeXitoi** [comment] 2024-05-08 14:32
Duplicate of #333

**Closed as completed by TeXitoi** 2024-05-08 14:32 UTC
